const heroPhrases: string[] = [
    "Discover, Join, and Thrive at Every Event!",
    "Elevate Your Experience: Where Events Come to Life!",
    "Your Pass to a World of Experiences!",
    "Unlock the Pulse of Every Gathering!",
    "Where Every Moment Becomes an Event!",
    "Dive into a World of Endless Events!",
    "Empower Your Social Calendar with Us!",
    "Embrace the Future of Event Exploration!",
    "Experience the Magic of Live Gatherings!",
    "Create Memories, One Event at a Time!",
    "Unleash the Adventure of Eventful Living!",
    "Crafting Connections, One Event Away!",
    "Ignite Your Journey with Exciting Events!",
    "Your Passport to Unforgettable Moments!",
    "Elevate Your Lifestyle with Us!",
    "Where Every Event is a New Story!",
    "Fueling Your Passion for Events!",
    "Open the Door to Event Excellence!",
    "Join, Connect, Celebrate!",
    "Life's Best Moments, All in One App!",
    "Where Dreams Meet Events!",
    "Discover the Joy of Event Discovery!",
    "Elevating Your Event Experience!",
    "Where Memories Are Born and Shared!",
    "Your Ultimate Event Companion!",
    "Redefining the Way You Attend Events!",
    "Weaving Moments into Memories!",
    "Journey Through Events, Your Way!",
    "Uniting People, Event by Event!",
    "Discover, Connect, and Thrive!",
    "Bridging Lives Through Events!",
    "Exploring Events, Making Memories!",
    "Adventure Awaits at Every Event!",
    "Your Ticket to Unforgettable Experiences!",
    "Crafting Your Eventful Story!",
    "Events: Where Dreams Take Shape!",
    "Unlocking Doors to Eventful Joy!",
    "We're Your Pathway to Fun and Joy!",
    "The App for Event Enthusiasts!",
    "Creating Moments, One Event at a Time!",
    "Where Event Magic Comes Alive!",
    "Your Journey, Our Events!",
    "Experience Life, One Event at a Time!",
    "Elevate, Explore, Enjoy!",
    "Every Event, an Opportunity!",
    "Your Hub for Epic Events!",
    "Connecting Through Events!",
    "Where Experiences Blossom!",
    "Eventful Living Starts Here!",
    "Navigating the World of Events!",
    "We're Your Event Ecosystem!",
    "Seize the Moments, Embrace the Events!",
    "Experience Beyond Imagination!",
    "Fueling Your Passion for Eventful Living!",
    "Unveil the Magic of Every Event!",
    "Elevate Your Social Scene with Us!",
    "Your Journey to Event Nirvana!",
    "Unlocking the Power of Events!",
    "Join the Event Revolution!",
    "Where Events Reside, Dreams Thrive!",
    "Creating Connections, One Event at a Time!",
    "Life's Best Moments, All in One Place!",
    "Fueling Adventures, One Event at a Time!",
    "Elevate Your Lifestyle with Every Event!",
    "Bringing Events to Your Fingertips!",
    "Event Discovery, Redefined!",
    "Unlock the Essence of Events!",
    "Your Gateway to Eventful Memories!",
    "Embark on a Journey of Events!",
    "Weaving Stories Through Events!",
    "Journey Through Every Event!",
    "Your Eventful Social Calendar!",
    "Crafting Memories, One Event at a Time!",
    "Enriching Lives, One Event at a Time!",
    "Event Bliss Begins Here!",
    "Every Event is an Adventure!",
    "Bringing People Together Through Events!",
    "Your Epicenter of Eventful Living!",
    "Where Every Event is a Celebration!",
    "Fueling Passion for Event Discovery!",
    "The Pulse of Eventful Living!",
    "Discover, Connect, Celebrate, Repeat!",
    "Embark on Eventful Adventures!",
    "Crafting Moments, One Event at a Time!",
    "Unlocking Eventful Possibilities!",
    "Life's Best Moments, All in One App!",
    "Fueling Joy Through Event Exploration!",
    "Elevate Your Lifestyle with Every Event!",
    "Creating Connections, One Event at a Time!",
    "Explore, Connect, Celebrate!",
    "Where Dreams Meet Reality Through Events!",
    "Ignite Your Passion for Eventful Living!",
    "Your Key to Unforgettable Moments!",
    "Elevate Your Event Experience with Us!",
    "Where Memories Are Made and Shared!",
    "Your Ultimate Guide to Eventful Living!",
    "Redefining Your Event Experience!",
    "Weaving Moments into Unforgettable Memories!",
    "Journey Through Every Event with Us!",
    "Unite, Celebrate, and Thrive!"
  ];
  
export default heroPhrases;